### ISSUE TITLE
SSL error handling

### ISSUE THREAD

**Issue by alorandos** [Tony-Perri/MOVEit.MIT#3]
When connecting to a MIT server with self-signed or mismatched certificate an error is thrown.

`+ Connect-MITServer -Hostname $hostname -Credential $credObject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.Http.HttpRequestException:TypeName) [Connect-MITServer],
    RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Connect-MITServer`

A better error message in addition to an option to ignore certificate errors as a proposed solution.

**Comment by Tony-Perri** [comment]
v0.4.6 now supports the `-SkipCertificateCheck` parameter to `Connect-MITServer`.  PowerShell 7+ is required.
